kind: Pod
apiVersion: v1
metadata:
  name: stress
spec:
  containers:
  - image: saivinaylt/stress:v1
    name: stress
    command: ["sleep", "2000"]
    resources:
    #soft limit when the container was create it create with this resources
      requests:
       # no of cores
        cpu: "0.3"
        # ram
        memory: "126mi"
    # its a hard limit the resources will go up to this levels    
      limits:
        cpu: "0.5"
        # up to ram
        memory: "150mi"
