kind: Pod
apiVersion: v1
metadata:
  name: stress
spec:
  containers:
  - image: saivinaylt/stress:v1
    name: stress
    command: ["sleep", "2000"]
    resources:
      requests:
        cpu: "0.2"
        memory: "126Mi"
      limits:
        cpu: "0.5"
        memory: "150Mi"
